export const category = [
  {
    id: 1,
    title: "Burger",
    img: require("../assets/images/burger.png"),
  },
  {
    id: 2,
    title: "Carribean",
    img: require("../assets/images/carb.png"),
  },
  {
    id: 3,
    title: "FastFood",
    img: require("../assets/images/fast.png"),
  },
  {
    id: 4,
    title: "French",
    img: require("../assets/images/french.png"),
  },
  {
    id: 5,
    title: "American",
    img: require("../assets/images/send.png"),
  },
];

export const featured = {
  id: 1,
  title: "Tested",
  description: "Tested Tested",
  restaurants: [
    {
      id: 1,
      name: "Test",
      image: require("../assets/images/bugg.png"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "sanzona sanzona",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
      ],
    },
    {
      id: 2,
      name: "Test",
      image: require("../assets/images/bugg.png"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "sanzona",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "vaso vaso vaso",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Test",
      image: require("../assets/images/bugg.png"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/bugg.png"),
        },
      ],
    },
  ],
};
